USE boombox;

-- Add comments later
CREATE TABLE Review(
    REVIEW_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID INT UNSIGNED NOT NULL,
    LIKE_COUNT INT NOT NULL,
    DISLIKE_COUNT INT NOT NULL,
    CREATION_DATE DATE NOT NULL,
    FOREIGN KEY(ACCOUNT_ID) REFERENCES Acct(ACCOUNT_ID)
);

CREATE TABLE MusicReview(
    REVIEW_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    MUSIC_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(REVIEW_ID) REFERENCES Review(REVIEW_ID),
    FOREIGN KEY(MUSIC_ID) REFERENCES music(MUSIC_ID)
);

CREATE TABLE AlbumReview(
    REVIEW_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ALBUM_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(REVIEW_ID) REFERENCES Review(REVIEW_ID),
    FOREIGN KEY(ALBUM_ID) REFERENCES album(ALBUM_ID)
);